### ISSUE TITLE
觉得修改方案不合适，这块想要修改合适是不是只能修改源码？有相对的源码修改方案嘛？

### ISSUE THREAD

**Issue by bluefogit** [LiteAVSDK/TRTC_UnrealEngine#2]
![image](https://user-images.githubusercontent.com/31725225/197163137-41cf0e45-89e4-4b36-a47e-b5ffb0dccbe7.png)
这个问题是不是unreal全局重载了new/delete导致的？加了这段代码是通过宏的方式来避免
<img width="731" alt="企业微信截图_6b5bf08a-cd84-487e-96a0-8d683805ebb8(1)" src="https://user-images.githubusercontent.com/31725225/197165691-33300b58-f526-4371-b8f0-c628a1d3e2d7.png">
假如加了这段宏，在IOS上使用会不会有性能问题？
我觉得还是用修改引擎源码的方案来修改这个问题比较合适，你们有什么更好的建议吗？

**Comment by bluefogit** [comment]
假如有如何修改源码的方案，请告知。谢谢

**Comment by c1aviennn** [comment]
在 iOS 平台，虚幻引擎默认使用内置的 Binned 内存分配器，相关源码可以参考 `FApplePlatformMemory::BaseAllocator()`。

这里通过全局宏定义设置引擎在 iOS 平台使用标准 C 的内存分配方式，也就是直接调用malloc、free、realloc等函数，以此来规避在 iOS 平台使用 TRTC 插件时一些内存异常释放问题；

关于 Ansi 与 Binned 两种内存分配的性能差异：Binned 对小内存的使用优化相对 Ansi 要好些，但是整体内存占用也会高一些，在中高档 iOS 设备上两者整体性能差异不明显。

如果希望在 iOS 平台使用 Binned 的同时使用 TRTC Plugin，暂时没有现成的方案，欢迎一起交流讨论～

**Comment by oneSitDown** [comment]
我其实是期望通过修改源码的方式来兼容binned的，这样感觉有点杀鸡用牛刀了
